#ifndef APPLICATIONCONSTANTS_H
#define APPLICATIONCONSTANTS_H

#define CAMERA_COLOR_STREAM_WIDTH 640
#define CAMERA_COLOR_STREAM_HEIGHT 480
#define CAMERA_IR_STREAM_WIDTH 320
#define CAMERA_IR_STREAM_HEIGHT 240
#define DISPLAY_DEFAULT_WIDTH 1920
#define DISPLAY_DEFAULT_HEIGHT 1080

#endif // APPLICATIONCONSTANTS_H
